/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TetrisSwingPackage;

import PlayBoardAndShapes.PlayBoard;
import PlayBoardAndShapes.ThreadMovingDown;
import java.awt.event.ActionEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.KeyStroke;


/**
 *
 * @author Jozef
 */ 
public class PlayBoardJFrame extends javax.swing.JFrame {

    /**
     * Playboard
     */
    private PlayBoard playBoard=new PlayBoard();
           
    Action downArrow;
    Action rightArrow;
    Action leftArrow;
    Action rotateShape;
   // ThreadMovingDown threadMovingDown=new ThreadMovingDown("Druhé");
    private int speed;
    ////make it much more better than for 1000 repeating cycle
    Thread automaticMovingDownThread = new Thread(() -> {
        for (int i = 0; i < 1000; i++) {
            
        
                 
        try {
                             Thread.sleep(speed);
                         } catch (InterruptedException ex) {
                             Logger.getLogger(PlayBoardJFrame.class.getName()).log(Level.SEVERE, null, ex);
                         }
                         updateScreen("down");
        }                }, "Druhe");
    
    private int speedLevel;
    //Vlakno threadForRepainting;
    /**
     * Creates new form MainJFrame
     */
    public PlayBoardJFrame() {
        initComponents();
         
        downArrow=new MoveDownBindingAction();
        rightArrow=new MoveRightBindingAction();
        leftArrow=new MoveLeftBindingAction();
        rotateShape=new RotateShapeBindingAction();
        
        /*jPanel1.getInputMap().put(KeyStroke.getKeyStroke("UP"), "downArrow");
        jPanel1.getActionMap().put("downArrow", downArrow);
        jPanel1.getInputMap().allKeys();
        jPanel1.getActionMap().allKeys();*/
        //move down
        jButton1.getInputMap().put(KeyStroke.getKeyStroke("DOWN"), "downArrow");
        jButton1.getActionMap().put("downArrow", downArrow);
        //move right
        jButton1.getInputMap().put(KeyStroke.getKeyStroke("RIGHT"), "rightArrow");
        jButton1.getActionMap().put("rightArrow",rightArrow );
        //move left
        jButton1.getInputMap().put(KeyStroke.getKeyStroke("LEFT"), "leftArrow");
        jButton1.getActionMap().put("leftArrow", leftArrow);
        
        //rotate shape
        jButton1.getInputMap().put(KeyStroke.getKeyStroke("SPACE"), "spaceKeyToRotate");
        jButton1.getActionMap().put("spaceKeyToRotate", rotateShape);
        
        //threadForRepainting = new Vlakno("PrveVlakno");
        speed=1000;
        jComboBox1.setEnabled(true);
        this.speedLevel=1;
        
        
        
        
    }

    /**
     *
     * @param direction
     */
    public void updateScreen(String direction){
            playBoard.inputShapeToPlayboard(direction);
            jLabel1.setText(Integer.toString(playBoard.getScore()));//shows actual score
            jTextField1.setText(direction);
            jPanel1.repaint();
            

    }
    
    /**
     *
     */
    public class MoveDownBindingAction extends AbstractAction{

        /**
         *Moving down
         * @param e Action event of moving down
         */
        @Override
        public void actionPerformed(ActionEvent e) {
            updateScreen("down");
        }
    }
    
    /**
     *
     */
    public class MoveRightBindingAction extends AbstractAction{

        /**
         * Moving right
         * @param e Action event of moving right
         */
        @Override
        public void actionPerformed(ActionEvent e) {
            updateScreen("right");

        }
    }
        
    /**
     *
     */
    public class MoveLeftBindingAction extends AbstractAction{

        /**
         *Moving left
         * @param e Action event of moving right
         */
        @Override
        public void actionPerformed(ActionEvent e) {
            updateScreen("left");

        }
    }

    /**
     *Class for rotate a shape.
     */
    public class RotateShapeBindingAction extends AbstractAction{

        /**
         *Rotates a shape.
         * @param e Action event for rotate a shape
         */
        @Override
        public void actionPerformed(ActionEvent e) {
            playBoard.rotateAnyShape();
            jPanel1.repaint();
        }
    }
    
    /*  public class Vlakno extends Thread{
    
    public Vlakno(String name) {
    super(name);
    }
    
    @Override
    public void run() {
    repaint();
    }
    
    }*/
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new TetrisSwingPackage.Background(playBoard);
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tetris");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(800, 50));
        setLocationByPlatform(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("restart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Score:");

        jTextField1.setBackground(new java.awt.Color(204, 255, 51));
        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 22, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
                     updateScreen("down");
                     automaticMovingDownThread.start();
                     jComboBox1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                            updateScreen("right");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
//add your elements





playBoard.deleteScreenBorders();
        repaint();
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
           this.speed=1000-100*Integer.parseInt(String.valueOf(jComboBox1.getSelectedItem()));
           this.speedLevel=Integer.parseInt(String.valueOf(jComboBox1.getSelectedItem()));;
           playBoard.setSpeedBonusFromSpeedLevel(speedLevel);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     *Gets level of shape´s moving speed.
     * @return Level of shape´s moving speed, which is used also for counting current bonus in game.
     */
    public int getSpeedLevel() {
        return speedLevel;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayBoardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayBoardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayBoardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayBoardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayBoardJFrame().setVisible(true);
            }
        });
    }

    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
